### ISSUE TITLE
Циклическая ссылка в yaml файле на сам себя.

### ISSUE THREAD

**Issue by ZababurinSergei** [yandex-market/yandex-market-partner-api#4]
Я подключил в свагер openapi спецификацию.

Получил ошибку

```
Errors
Hide
 
Resolver error
Maximum call stack size exceeded
Resolver error
Cannot read properties of undefined (reading '$$ref')
Resolver error
Cannot read properties of undefined (reading 'properties')
Resolver error
Cannot read properties of undefined (reading 'properties')
Resolver error
Cannot read properties of undefined (reading 'properties')
Resolver error
Cannot read properties of undefined (reading '$$ref')
Resolver error
Maximum call stack size exceeded
```

Начал смотреть где это и нашел причину ошубки.

Она находится в файле  */openapi/components/schemas/RegionDTO.yaml*

```
description: Регион доставки.
type: object
required:
  - name
  - type
properties:
  id:
    description: Идентификатор региона.
    type: integer
    format: int64
  name:
    description: Название региона.
    type: string
  type:
    description: Тип региона.
    $ref: ./RegionType.yaml
  parent:
    description: |
      Информация о родительском регионе.

      Указываются родительские регионы до уровня страны.
    $ref: ./RegionDTO.yaml
  children:
    description: Дочерние регионы.
    type: array
    items:
      $ref: ./RegionDTO.yaml
```

В двух местах, ссылки стоят на сам файл, и получается циклическая ссылка.

```
 $ref: ./RegionDTO.yaml
```

Как поправить этот файл ?
